### ISSUE TITLE
Restart as admin on 1.5.1

### ISSUE THREAD

**Issue by gjstockham** [DonJayamanne/gitHistoryVSCode#33] opened 2016-09-12 08:16 UTC
Referencing issue https://github.com/Microsoft/vscode/issues/11739

On the latest update to VS Code, I get prompted to restart VS Code as admin to use git history, even when I am already running as administrator.  I haven't managed to get it to work at all.

VS Code 1.5.1,  Windows 10, Git History 0.0.10

**Comment by DonJayamanne** [comment] 2016-09-12 08:31
@gjstockham , please could you upload a screenshot of the error/message displayed. I'd like to understand when and where this message is displayed.

**Comment by gjstockham** [comment] 2016-09-12 09:02
After some investigation, this may be something to do with an interaction between Git History and the VS Icons extension.

Running as administrator, and running the git log command:

![screenshot 2016-09-12 09 46 21](https://cloud.githubusercontent.com/assets/310862/18430265/a370c00a-78cf-11e6-978e-f5d706d90bb3.jpg)

![screenshot 2016-09-12 09 58 24](https://cloud.githubusercontent.com/assets/310862/18430272/acf22790-78cf-11e6-9862-1091eae30c55.jpg)

I get prompted continuously whenever I use git history, but never for anything else (after the initial vscode-icons setup).

If I uninstall the vscode-icons extension, I do not get prompted to run as administrator, but the git history extension seems to hang, and never returns anything.

**Comment by DonJayamanne** [comment] 2016-09-12 09:09
Interesting, will check this out asap. Thanks for the info

**Comment by DonJayamanne** [comment] 2016-09-12 10:29
@gjstockham , I have tested this at my end with and without the extension and am unable to replicate this. Please could you confirm the following doesn't work:
- Uninstalling the VS Code Icon extension
- Restarting VS Code
- Testing the Git History

If the above doesn't work, then the issue isn't related to VS Code Icons.
FYI - The message "Run VS Code with admin..." message is displayed by the VS Code Icon extension and not part of this Git History extension.

**Comment by gjstockham** [comment] 2016-09-12 11:25
I've done a complete re-install of VS Code.  Without the icons extension, I don't get the admin prompt, but I still get nothing from git history.  It looks like it is hanging.

**Comment by DonJayamanne** [comment] 2016-09-12 11:30
@gjstockham 
So, that's a different issue #34. Lets close this and create a separate issue so we don't get confused.

**Closed by DonJayamanne** 2016-09-12 11:30 UTC
