### ISSUE TITLE
can't use the compare the file with old one on linux fedora

### ISSUE THREAD

**Issue by JWleo** [DonJayamanne/gitHistoryVSCode#291] opened 2018-07-11 02:22 UTC
my os is fedora 21.After clicking the "Compare against workspace file", nothing happened.
But the one on window is just fine

**Comment by RevFry** [comment] 2018-07-11 18:04
In the last week I've run into this issue as well. I'm on windows 8 and windows 10. I applied the latest 7/5/2018 patch for VSCode 1.25.0. I can't say for sure but it seems that things stopped fully working around that update.

**Comment by JWleo** [comment] 2018-07-12 01:47
@RevFry that' right. it works on 1.24.1,but stopping running on 1.25.0.

**Comment by JWleo** [comment] 2018-07-12 02:16
@slowvoid it's a temporary solution to install the 1.24.1 again.

**Comment by STUkh** [comment] 2018-07-12 10:04
Doesn't work too

OSX 10.13.5
VScode Version 1.25.0 (1.25.0)

**Comment by JWleo** [comment] 2018-07-12 15:06
@RevFry I hope so. @DonJayamanne please fix the bug to make the one better

**Comment by DonJayamanne** [comment] 2018-07-13 17:34
Please could one of you provide a repo to replicate this?

**Comment by slowvoid** [comment] 2018-07-13 18:48
@DonJayamanne You can use this repo: https://bitbucket.org/JoaoVitorLopesCabral/tms-self-optimizing-graphs/overview

Let me know if you have any issues using it. 
Thanks

**Comment by DonJayamanne** [comment] 2018-07-17 16:00
Closing as a duplicate of #293, new version will be released soon

**Closed by DonJayamanne** 2018-07-17 16:00 UTC
