### ISSUE TITLE
Not rendering newlines in commit messages

### ISSUE THREAD

**Issue by plwalsh** [DonJayamanne/gitHistoryVSCode#608] opened 2020-11-11 01:28 UTC
In the latest v0.6.13, newlines have stopped rendering properly in the body of a commit message, after clicking on a particular commit to view its details.

For example, if the commit message was written like this:
```
Fix bug in library

- add missing piece of code
- remove incorrect function
- call correct function
```

It shows up like this in details view:
```
(Heading)     Fix bug in library
(Subheading)  <author> on <date>

(Body)        - add missing piece of code - remove incorrect function - call correct function
```

When it should show up like this:
```
(Heading)     Fix bug in library
(Subheading)  <author> on <date>

(Body)        - add missing piece of code
              - remove incorrect function
              - call correct function
```

**Comment by ole1986** [comment] 2020-11-11 05:00
Dup with #601 and possibly fixed with PR #600 which is not yet released

**Comment by plwalsh** [comment] 2020-11-11 05:14
It looks like #601 is inserting newlines (`\n`) that didn't exist in the original message in order to artificially wrap at a specified width. This issue is regarding newlines that existed in the original commit message but are being stripped out and converted to single spaces, causing the individual lines to concatenate. I don't know if your PR addresses that as well.

**Comment by ole1986** [comment] 2020-11-11 05:24
Good hint... But that is odd since a forced line break should always do the right thing...

I will double check it.

Is your environment a Linux or windows machine you encountered this issue?

**Comment by plwalsh** [comment] 2020-11-11 05:33
I'm running vscode-insiders (latest version) locally on a Windows machine, but using the `Remote Development - SSH` extension to connect to vscode-remote on a Linux machine.

I agree that it's odd, since I would expect the line breaks to come right through unmodified. I write all of my commit messages like the example in the OP, and I know they used to show up perfectly fine in your extension quite recently.

**Comment by ole1986** [comment] 2020-11-11 15:26
Fixed, ..ups..

**Closed by ole1986** 2020-11-11 15:26 UTC

**Comment by plwalsh** [comment] 2020-11-11 16:25
Awesome, thanks so much! This is one of my most used extensions, great work on it!

**Comment by rob3c** [comment] 2020-11-18 21:58
Hi, I don't think this is quite working yet, so closing the issue seems premature.

The referenced commit tagged with v0.6.14 does not fix newline rendering for me on WIndows with v0.6.14 of the Git History extension. However, running `git log` in a Windows Command Prompt renders the newlines just fine, so I know they're there. If it helps, the commit messages were created within vscode itself in the Source Control tab.

With newlines ignored, the commit messages are treated as one single long line. While that single line is wrapped in this version, wrapping long lines is not the same as respecting newlines, so this is not a duplicate of #601.

**Comment by plwalsh** [comment] 2020-11-18 22:38
@rob3c That's odd; the v0.6.14 update fixed the problem for me.

I wonder if your issue has to do with not leaving a blank line between your first line ("title line") and the subsequent lines ("full commit message"). See [this explanation](https://chris.beams.io/posts/git-commit/#separate) for the reason why to do this, and [this git doc](https://git-scm.com/docs/pretty-formats) for how git defines the sections.

If you're seeing the "one single long line" appear above your author name and commit date, that's what's happening. This extension renders the title line at the top, followed by the author and commit date, and then lastly the body of the message. You would see a similar one single long line if you ran `git log --oneline` in a command prompt.

**Comment by rob3c** [comment] 2020-11-19 08:04
@plwalsh Good catch! Blank lines were missing after the title lines - thanks!
