### ISSUE TITLE
history not working after 0.6.x

### ISSUE THREAD

**Issue by FWcloud916** [DonJayamanne/gitHistoryVSCode#482] opened 2020-03-06 02:46 UTC
Issue Type: <b>Bug</b>

just open history and nothing show
![hist](https://user-images.githubusercontent.com/20121433/76045314-a91a6080-5f97-11ea-949d-ce4f0a107100.png)
![hist2](https://user-images.githubusercontent.com/20121433/76045315-aa4b8d80-5f97-11ea-9ccb-d53f455cec54.png)
![image](https://user-images.githubusercontent.com/20121433/76046202-437ba380-5f9a-11ea-92c7-bfc4ad8c5b3c.png)

Extension version: 0.6.1
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           X5570  @ 2.93GHz (4 x 2933)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|10.00GB (5.12GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/user/Documents/property/property_chattel|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DonJayamanne** [comment] 2020-03-06 03:21
Is this a public git repo, one that we could use to replicate this issue?
Please open `Developer Open Webview developer tools`, go into the console window and provide the contents of the output.
If not a public repo, please could you, create a git repo with similar commits that could help us identify this issue.

Thanks and apologies for this issue.

**Comment by FWcloud916** [comment] 2020-03-06 03:40
![image](https://user-images.githubusercontent.com/20121433/76046202-437ba380-5f9a-11ea-92c7-bfc4ad8c5b3c.png)

**Comment by FWcloud916** [comment] 2020-03-06 03:44
I tried every repo, public and private, my repo or other developers' had same question
AND no other error is output.

**Comment by DonJayamanne** [comment] 2020-03-06 03:54
Please could you provide an example of one such public repo. Thanks

**Comment by FWcloud916** [comment] 2020-03-06 03:58
Maybe this: https://github.com/FWcloud916/kk-api-node

**Comment by ole1986** [comment] 2020-03-06 07:30
@FWcloud916 could you please post the git cmdlet version you are currently using?

**Comment by FWcloud916** [comment] 2020-03-06 08:46
![image](https://user-images.githubusercontent.com/20121433/76067132-d5e76b80-5fc9-11ea-9518-a09477e03ffb.png)

My  git cli version is 2.25.0

**Comment by ole1986** [comment] 2020-03-06 09:10
Can you please double check your git History preferences?

![image](https://user-images.githubusercontent.com/4850116/76069029-89346e00-5f92-11ea-8648-bcd34008517a.png)

Especially the `gitHistory.pageSize`

**Comment by FWcloud916** [comment] 2020-03-06 09:38
![image](https://user-images.githubusercontent.com/20121433/76071469-3f1ead00-5fd1-11ea-995a-087d5d6450fb.png)

**Comment by hoegge** [comment] 2020-03-06 16:26
Mine does also not work suddenly. When I ask for a line history I get this in the console. Git 2.25.1 on Windows, VScode 1.42.1. No preferences set for the extension.

```sh
git shortlog -e -s -n HEAD  (completed in 0.245s)
git log -L16,16:projects/gudena-app-ui/src/pages/SpecimenCollection/Source/Input.tsx --full-history --pretty=oneline --date-order --decorate=full --skip=0 --max-count=10  (completed in 0.418s)
git rev-list --full-history --count  (completed in 0.129s)
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=<n>
    --max-age=<epoch>
    --min-age=<epoch>
    --sparse
    --no-merges
    --min-parents=<n>
    --no-min-parents
    --max-parents=<n>
    --no-max-parents
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --[no-]object-names
    --abbrev=<n> | --no-abbrev
    --abbrev-commit
    --left-right
    --count
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
```

**Comment by ole1986** [comment] 2020-03-06 16:36
According to the issue author it was related to the "Git: view history" command.

Can you confirm this or does it only cause an error when you try to use line history?

**Comment by ole1986** [comment] 2020-03-06 19:37
@FWcloud916 
Would you kindly double check the "Git History" output and post the content here?

**Comment by FWcloud916** [comment] 2020-03-07 00:32
@ole1986 
Output is empty

**Comment by ole1986** [comment] 2020-03-07 13:09
What about the output of the `Git` window. Is it empty, too?

**Comment by FWcloud916** [comment] 2020-03-07 14:00
yes.
No new output, when I use git history

**Comment by FWcloud916** [comment] 2020-03-07 14:03
But I try another computer, git history is work fine.
Possibly, bug is on my computer,right?

**Comment by ole1986** [comment] 2020-03-07 14:07
I think so.. have you already tried to reinstall the Git cli and extension?

**Comment by FWcloud916** [comment] 2020-03-08 02:49
yes,I have reinstalled git and vscode

**Comment by DonJayamanne** [comment] 2020-03-08 05:02
@FWcloud916 
Does this work if you install a previous version of the extension. Must likely an issue with encoding.

Please open `Developer Open Webview developer tools`, go into the console window and provide the contents of the output. Ensure you select the command with the text  `Webview`. That will contain more details of the error.

**Comment by FWcloud916** [comment] 2020-03-10 01:37
I got this.
version 0.6.2
![image](https://user-images.githubusercontent.com/20121433/76270967-096c1380-62b2-11ea-87db-750877ca0ff3.png)

**Comment by DonJayamanne** [comment] 2020-03-10 01:56
@FWcloud916 I think i know what's wrong there. I have a fix for this.
Thanks again, specially for your patience. Will try to get this out soon.

@ole1986 I believe this is due to the fact that `vscode.git` extension hasn't been activated. I've seen this as well.

**Comment by aehimself** [comment] 2020-03-15 18:25
If you guys need more examples, JVCL git repo shows up empty too: https://github.com/project-jedi/jvcl.git
git version 2.25.1.windows.1
Git History 0.6.2

Would be nice to see a fix, our repo at work got empty too, forcing me to temporarily switch extensions which I don't like :)

**Comment by DonJayamanne** [comment] 2020-03-15 21:33
Will look into this today and try to get a fix out asap

**Comment by DonJayamanne** [comment] 2020-03-16 00:42
@aehimself Tested at my end and it works as expected.
We'll be releasing a new version around tomorrow. Please do test that.
If it doesn't work, please do the following:
* Open GitHistory and then open `Developer: Toggle Developer Tools`
	* Go into `console window`, save contents to a file and upload here
	* Console window contains stack trace and details of the error
* Open GitHistory and then open `Developer: Open Webview Developer Tools`
	* Go into `console window`, save contents to a file and upload here
	* Console window contains stack trace and details of the error

Note: Both error logs are different and vital to identifying the cause of the issue.

**Comment by aehimself** [comment] 2020-03-18 07:25
Hello,
0.6.3 still shows an empty tree, please see the logs attached:

[Desktop.zip](https://github.com/DonJayamanne/gitHistoryVSCode/files/4347535/Desktop.zip)

Thank you!

**Comment by aehimself** [comment] 2020-04-25 08:47
0.6.4 is still affected.

**Comment by ole1986** [comment] 2020-04-25 09:56
@aehimself I just tested with the jvcl repository using the following setup

![image](https://user-images.githubusercontent.com/4850116/80276861-a14f8080-86eb-11ea-98d9-8905dc2c9780.png)

Git version: 2.11
vscode version: 1.44.2
Git History version: 0.6.4

Would you kindly open the Developer Tools (as described above by @DonJayamanne ) and look at possible errors?

Thank you

**Comment by aehimself** [comment] 2020-04-27 10:23
Git version 2.26.2.windows.1
vscode version: 1.44.2
Git History version: 0.6.4

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4811 [Embedded Page] [object Object]
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4811 [Embedded Page] Uncaught (in promise) TypeError: t.payload is not iterable


<%2Fhtml>:1 Uncaught (in promise) Object
bundle.js:47 Object
bundle.js:47 Object
bundle.js:47 Uncaught (in promise) TypeError: t.payload is not iterable
    at FETCHED_AVATARS (bundle.js:47)
    at bundle.js:15
    at bundle.js:47
    at Array.reduce (<anonymous>)
    at bundle.js:47
    at bundle.js:47
    at bundle.js:6
    at m (bundle.js:6)
    at bundle.js:47
    at bundle.js:15
bundle.js:47 Object

[Desktop.zip](https://github.com/DonJayamanne/gitHistoryVSCode/files/4539006/Desktop.zip)

**Comment by aehimself** [comment] 2020-04-28 06:44
Yayy!!! 0.6.5 made our work repository to show up again!!!
Thank you!

**Closed** 2020-04-28 15:58 UTC
Labels: bug
