### ISSUE TITLE
huge CPU spike when opening git history in version 0.5.x

### ISSUE THREAD

**Issue by ole1986** [DonJayamanne/gitHistoryVSCode#439] opened 2020-02-13 21:37 UTC
I'm seeing a huge CPU spike when I try to view the history after the latest update.

_Originally posted by @chrisbarnes

**Comment by ole1986** [comment] 2020-02-13 21:39
@chrisbarnes does the CPU spike also occurs when refreshing the history view only?

**Comment by ole1986** [comment] 2020-02-14 11:13
@chrisbarnes Also you could try to reduce the number of items being loaded through the setting `gitHistory.pageSize`

![image](https://user-images.githubusercontent.com/4850116/74526284-5531d400-4f23-11ea-8158-3097332e9eec.png)

**Comment by ole1986** [comment] 2020-02-15 10:16
A possible other reason might be that the `bundle.js` file size has increase from ~600 kb to ~2 mb  only because of a single image used from the react-icons package.

I have replaced this to only use Github octicons to recover the file size.

**Comment by ole1986** [comment] 2020-02-17 11:28
did the last update (0.5.3) resolved the cpu issue?

**Comment by chrisbarnes** [comment] 2020-02-17 17:49
@ole1986 it doesn't look like the issue was fixed with the latest update. It looks like while the extension is loading or refreshing the git history it is spawning tons of these Git for Windows and Console Window Host processes. 

![image](https://user-images.githubusercontent.com/642906/74676371-e69f8100-5183-11ea-9db7-56a8f44d6508.png)

**Comment by ole1986** [comment] 2020-02-17 18:43
It looks like git processes are not exiting for some reason... (most of them seem to be spawned by the git extension api)

Do you have further info about the versions you are using? vscode, git cmd, extension

What you can try is to check the "Git" output window and eventually run the commands manually to see what process not existing

![image](https://user-images.githubusercontent.com/4850116/74679173-5d0ca500-51bd-11ea-9d1c-04aeee6fa1d7.png)

**Comment by ole1986** [comment] 2020-02-21 16:18
@chrisbarnes 

Did you had the chance to find out the reason why so many processes are being spawned?
Is this still an issue and if not can you remember what you did to resolve it?

**Comment by DonJayamanne** [comment] 2020-03-12 03:52
I think this is a dup of #492

**Comment by DonJayamanne** [comment] 2020-03-16 00:46
I tested the old version on Windows and can see the CPU spikes due to the large number of git processes. THis has been resolved in the development version and will be release soon. Closing for now as the issue has been resolved, even though the fix hasn't been released to the marketplace.

@chrisbarnes Please be patient, we'll release something within a day or so.

**Comment by DonJayamanne** [comment] 2020-03-16 00:46
That being said, if the issue isn't resolved after version 0.6.3, please do feel free to re-open or create a new issue.

**Closed by DonJayamanne** 2020-03-16 00:46 UTC
Labels: bug
