### ISSUE TITLE
git.path config setting causes endless loop

### ISSUE THREAD

**Issue by snraets** [DonJayamanne/gitHistoryVSCode#78] opened 2016-12-13 16:41 UTC
Command just seems to put the tab into a long loop, and does not create the history graph.

Is there a version of Git that I need to install?

I am working on Windows and my development is on a shared drive.

**Comment by mikes-gh** [comment] 2016-12-13 16:45
What version of extension please and what OS

**Comment by mikes-gh** [comment] 2016-12-13 16:49
Shared drives are slower as git is file intensive.
But I have a repo on a samba share and it works ok.

**Comment by marcelh-gh** [comment] 2016-12-19 11:50
I have the same issue as reported in the op.

VS Code 1.8.0
Git 2.11.0
Git History Extension 0.1.4

Re-installing the extension did not help. Repository is local and very small.

Also, the view file history feature does not do anything at all.

**Comment by mikes-gh** [comment] 2016-12-19 13:01
What OS please

**Comment by marcelh-gh** [comment] 2016-12-19 13:03
Windows 10 (14393.576)

**Comment by mikes-gh** [comment] 2016-12-19 13:11
OK I have tested only on windows 7 fedroa 25 and OSX
I know windows 10 has built in ubuntu bash I wonder if its something to do with that.
Has it ever worked or this your first time using the extension?

**Comment by mikes-gh** [comment] 2016-12-19 13:12
In the integrated terminal could you do 

>where git

**Comment by marcelh-gh** [comment] 2016-12-19 13:15
first of all thank you for the quick feedback and testing! :)
I have installed the extension for the first time and was really looking forward to using it. Unfortunately it has never worked so far.

where git point to a:\Programs\Git\cmd\git.exe (that's where I have installed Git via the Windows installer.

**Comment by marcelh-gh** [comment] 2016-12-19 13:19
BTW I have also installed the GITLens (1.3.1) extension and that one works flawlessly (including displaying the history for files).

First I thought, maybe the two extensions are somehow inhibiting each other. So I uninstalled GITLens but that did not fix the problem.

**Comment by mikes-gh** [comment] 2016-12-19 13:21
Curious is that a type or it really on the A: drive letter?

**Comment by marcelh-gh** [comment] 2016-12-19 13:24
not a typo (virtual drive on an SSD), no floppy disk! ;-)

**Comment by mikes-gh** [comment] 2016-12-19 13:48
OK thanks for your continued help I am thinking our git executable logic may be flawed here.  Its disappointing to see we are not even working out the box on a seemingly simple setup.  
We default to the registry on windows could you let me know the value of

`reg query HKLM\SOFTWARE\GitForWindows`

Perhaps the slightly less common path of a: may be a factor.

**Comment by marcelh-gh** [comment] 2016-12-19 14:09
it shows:
CurrentVersion: 2.11.0
InstallPath: a:\Programs\Git
LibexecPath: a:\Programs\Git\mingw64\libexec\git-core

**Comment by mikes-gh** [comment] 2016-12-19 14:27
All seems in order.
Is your repo on github?  Could I test?

**Comment by marcelh-gh** [comment] 2016-12-19 14:30
no, its just local. i am starting to think the problem might be with Git.
I uninstalled and tried to install again. Just like the first time the installation stalls at the very end and never finishes (although as I said it still was working just fine).
I thought it might have been caused by AV SW (since it reported one of the tmp files during installation) but even with the AV off the installation doesn't go through correctly.

I'll see if installing an older version of Git helps...

**Comment by mikes-gh** [comment] 2016-12-19 14:37
If git lens works I suspect its our end.  I would like to clear this up though as its really bad if we dont work out the box.  You could runt he installer with  /LOG=gitinstall.log

**Comment by marcelh-gh** [comment] 2016-12-19 14:38
Ok, using the old version did not help. It actually seems the Git installer for Windows has a problem with the A: path. I am back on the 2.11 version now. Installed with all settings left as standard - so on C:

The behaviour is all the same: Git works, GitLens works. GitHistory does not.

**Comment by mikes-gh** [comment] 2016-12-19 14:42
Would you be willing to share your repo on your github account?

**Comment by marcelh-gh** [comment] 2016-12-19 14:45
I just created a new repository. Just an empty folder. added one single little text file to the repo. did one change and committed.

The behaviour is the same. So it has nothing to do with my repo. And just to be sure I did this test on the C drive.

So I guess in order for you to replicate the issue you just need to try on the Win10 platform. Maybe the Ubuntu bash is the problem(?)

**Comment by mikes-gh** [comment] 2016-12-19 14:49
Actually thinking about it ubuntu bash shouldn't come into play here as we are spawning git directly.Can you double check

reg query HKLM\SOFTWARE\GitForWindows

now shows c: path

**Comment by marcelh-gh** [comment] 2016-12-19 14:50
yup. all set correctly.
Maybe the guys who wrote GitLens can help you...

**Comment by mikes-gh** [comment] 2016-12-19 15:03
I just did a new repo one file commit and it works here.
I'll setup windows 10 and try with that thanks for your help.

**Comment by mikes-gh** [comment] 2016-12-19 15:04
@DonJayamanne  are you using windows 10 git 2.11 ?

**Comment by marcelh-gh** [comment] 2016-12-19 15:21
oh and just to be clear: when I do "git log" in the internal console in VS, the log gets displayed. that does not look like it is an environment variable / path problem...

**Comment by snraets** [comment] 2016-12-19 15:37
Sorry, I was not a good citizen mentioning the issue, and then not responding to your question.

Windows 10 Pro Version 1511. Git version 2.10.1.  VS Code 1.8.0.

When I clone the repository to my C: drive, Git History (git log) works.

**Comment by mikes-gh** [comment] 2016-12-19 15:39
Sorry to keep asking but could you give me the powershell  output of

 $env:path.split(";")

**Comment by snraets** [comment] 2016-12-19 15:40
Is your question to me?

**Comment by mikes-gh** [comment] 2016-12-19 15:41
@snraets thanks for the extra info sorry didn't notice you popping in. Its for @marcelh-gh

**Comment by marcelh-gh** [comment] 2016-12-19 16:48
it seems the not really successful installations of Git left quite a mess in the environment variables. they showed strange behaviour even when trying to clean up.

However, now that everything is cleaned up (only entry in path is the git install folder on the c drive)....
the problem still exists: GITlens works fine as before and GIThistory does not work at all :(

**Comment by mikes-gh** [comment] 2016-12-19 16:57
Sorry about that.  Given that @snraets has it working on a local repo on windows 10 this must be environmental.  That's not to say git history is not at fault.  Its just going to be difficult to debug without your machine.  It shouldn't need path anyway as we read the registry for git path.

**Comment by marcelh-gh** [comment] 2016-12-19 16:59
well, @snraets is also running an older version of Win10. 
right now "where git" and the path variable both point to the same correct location. the registry entry is just as advised by you. So I don't see what else I could change. Also, the question remains, why all this has such an impact on GIThistory. since both Git itself and GITlens are both running just fine within VS code.

**Comment by mikes-gh** [comment] 2016-12-19 17:07
@marcelh-gh  Dont worry Im on your side :smile:  its just hard to know where to go next without out debuging it sat at your machine. 
Its still unclear to me though what results you get.

If you right click a file do you see `Git View File History`?
When you click on this what happens?

If you Alt shift P
and type git log then return

What happens?

**Comment by marcelh-gh** [comment] 2016-12-19 17:11
I appreciate your help! :-)

yes, if I right click on a file I see Git View File History in the context menu.
When I click on it, nothing happens at all.
When I call the git log via the command palette, a new tab opens with the header "Git History (git log)" and it keeps loading forever without ever displaying anything.

**Comment by mikes-gh** [comment] 2016-12-19 22:55
OK heres a long shot  you may be hitting this
#46 
Do you have git.path set in your vscode configuration settings.
GitLens doesn't use those but we do and don't seem to validate.

I just checked and if I set git.path to an invalid path I get your exact issue.

**Comment by mikes-gh** [comment] 2016-12-19 23:07
Deleting `git.path` it is there should be enough

**Comment by marcelh-gh** [comment] 2016-12-19 23:28
congrats! you found the cause of the problem! :-) thank you very much for your work!

I had actually looked for any invalid paths in the setting files myself and did not find any.
Based on your suggestion I searched for any Git related entries again and found that by default VS Code creates a Git.path entry and sets it to Null !
That is done in the user settings, so you can't easily delete it. When I changed Null to the filename + path of the git.exe everything started to work.

This will probably affect more users. So I suggest you either overwrite this setting during installation of the extension or at least advise the users to take care of it.
If you are in contact with the VS Code developers maybe they can take care of this when you press that button to enable Git in an existing VS Code project since at that point they know the path to the git.exe.

Thanks again and best regards,
Marcel

**Comment by mikes-gh** [comment] 2016-12-19 23:50
yes this is an issue we will address.
I am not sure about your settings though.
You shouldn't have to search for them.
They are under preferences

**Comment by mikes-gh** [comment] 2016-12-19 23:51
The default of null should still work

**Comment by marcelh-gh** [comment] 2016-12-20 11:24
at no point did I have any invalid path definition. it was the default null all along.

btw: I think all of this is a bit too much complexity for something as simple as a path to an executable.
if you think you still have to keep those three different possible sources (registry, env vars and VS Code config), here are two very simple suggestions:

#1: I have seen in your code that you actually rely on different sources for that path depending on the platform. so it would be a good idea to publish that information (which source is used on which platform) in the description of the extension. that would eliminate most of the hassle we had yesterday to find the cause
#2: implement a simple message to be displayed within VS code when the extension faces a problem which keeps it from running at all. that would take a lot of the 'mystery' out of issues like this one.

besides all this:
I really like the functionality of GitHistory. I am gonna be using it a lot! :-) thanks a lot

**Comment by mikes-gh** [comment] 2016-12-20 11:43
> btw: I think all of this is a bit too much complexity for something as simple as a path to an executable.
if you think you still have to keep those three different possible sources (registry, env vars and VS Code config), here are two very simple suggestions:

That complexity should mean simplicity for the end user.
For example Git for windows doesnt always install an entry in path depending on what option you chose.

What then?

Wouldn't you rather we looked up the path in the registry so you didn't have to start dealing with messages and manually configuring?

Also Git for windows can install as a non admin user in which case it is intalled in the users profile which isnt a well know path.

You may have more thatn one version of git on your machine (common for developers).
If you tell vscode which one you want to use wouldnt you rather our extension use that version as well?

The reasons above are why the 3 sources are used.  Its so the user doesnt have to do anything.
In this case we had a bug that we used `git.path` uncionditionally even if the path was invalid.
This is now fixed in the linked PR (may not get merged for a while becuase its Christams).

**Comment by mikes-gh** [comment] 2016-12-20 11:47
> implement a simple message to be displayed within VS code when the extension faces a problem which keeps it from running at all. that would take a lot of the 'mystery' out of issues like this one. :+1:

**Comment by marcelh-gh** [comment] 2016-12-21 21:02
Thanks for the explanation. I definitely get where you're coming from.
I personally would probably prefer to have to just configure the path somewhere (preferably VS Code) and then be done with it but I get that you want to make it work for multiple different scenarios right out of the box.
Thanks again for the effort in finding the problem!

Cheers,
Marcel

**Comment by mikes-gh** [comment] 2016-12-22 09:20
I understand your preference given the context of this bug, but if this bug was not present this issue  wouldn't exist .
So I think the current strategy is the best.

**Closed** 2017-01-05 17:46 UTC
Labels: bug
