### ISSUE TITLE
History view open file

### ISSUE THREAD

**Issue by bm-stschneider** [DonJayamanne/gitHistoryVSCode#156] opened 2017-08-21 12:25 UTC
It would be nice if there was an option to open the file from the commit in the history instead of only comparing it or viewing a tmp file.

**Comment by DonJayamanne** [comment] 2017-11-15 17:45
Duplicate of https://github.com/DonJayamanne/gitHistoryVSCode/issues/151

**Closed by DonJayamanne** 2017-11-15 17:45 UTC
