### ISSUE TITLE
[BUG] vscode 1.76.0 不显示分支名称了    no show branch name

### ISSUE THREAD

**Issue by HelloDBA** [DonJayamanne/gitHistoryVSCode#732] opened 2023-03-03 04:19 UTC
**Describe the Bug**

Description of what the bug is.不显示分支名称了    no show branch name
![微信截图_20230303121819](https://user-images.githubusercontent.com/11484786/222630387-b1737b5d-b10f-4dab-a16a-cefb09d7acf7.png)

**Steps To Reproduce**

1.
2.
3.

**Expected Behavior**

What you expected to happen.

**Environment**

 - OS: windows 10
 - VSCode version: 1.76
 - Git History version:0.6.19

**Comment by AdiIntel** [comment] 2023-03-03 17:23
I believe, this regression got introduced with VS Code v1.76 update.

**Comment by djshea33** [comment] 2023-03-03 17:45
I'm in the same boat.  Happened when I upgraded to VS Code v1.76.

**Comment by cyrusdaboo** [comment] 2023-03-03 20:30
Same issue here. Would appreciate a quick fix for this.

**Comment by BSanass** [comment] 2023-03-04 05:50
I'm facing the same issue. It started occurring after I upgraded to VS Code v1.76.

**Comment by ya-pekatoros** [comment] 2023-03-04 09:03
Yeah, exactly the same problem.

**Comment by sisaman** [comment] 2023-03-05 09:12
I'm having the same issue.

**Comment by DonJayamanne** [comment] 2023-03-05 09:14
Working on a fix now,

**Comment by DonJayamanne** [comment] 2023-03-05 09:14
Closing as a duplicate of #730

**Closed by DonJayamanne** 2023-03-05 09:14 UTC
