### ISSUE TITLE
Error "fatal: No such remote 'origin'"

### ISSUE THREAD

**Issue by VamshiKrishnaAlladi** [DonJayamanne/gitHistoryVSCode#237] opened 2018-02-13 10:05 UTC
I almost always rename the remotes to a custom one.

`git remote get-url origin  (completed in 0.148s)`
`fatal: No such remote 'origin'`

The error here is valid as the extension tries to run `git remote get-url origin` but there is no origin here.

Also, I usually have multiple remotes: one pointing to the actual repo listed under a GitHub organization and another pointing to the repo I forked.

It would be great if you can fetch the remote names first and then try getting the URLs.

**Side note:** This did not happen in the older versions.

**Comment by kron4eg** [comment] 2018-02-16 15:47
same here, every git history operation pops up "Output" panel with error:

```
git remote get-url origin  (completed in 0.011s)
fatal: No such remote 'origin'
```

**Comment by papa12804** [comment] 2018-03-13 09:53
Same problem.
I'm only using local repo, no remote repo existed.
Output panel always pops up and shows

`git remote get-url origin  (completed in 0.105s)`
`fatal: No such remote 'origin'`

**Comment by PaulCapestany** [comment] 2018-03-29 14:10
It looks as if a hacky/temporary fix to this issue is to comment out the calls to `logger.log` and `logger.error` within the source files for this extension, which I found at ~/.vscode/extensions/donjayamanne.githistory-0.4.0/ on my system. FWIW I assume that if/when there's an update to this extension you'd have to go in again and manually comment the logging lines out once more...

I'd imagine a better approach would be to allow for a preference that disables this behavior permanently (and/or better handles git repos that lack a remote origin). Having the "Output" panel constantly popping up when using this otherwise great extension can get a bit annoying :)

**Comment by DonJayamanne** [comment] 2018-05-06 05:10
Closing as a duplicate of #253

**Closed by DonJayamanne** 2018-05-06 05:10 UTC

**Comment by VamshiKrishnaAlladi** [comment] 2018-05-07 06:09
The issue is not fixed yet. Also, I did not understand how the changes in the PR #268 would work, as you wrapped a promise in a try-catch block. Am I missing anything here?

**Comment by dustinmoris** [comment] 2018-08-12 08:11
Please see #281 for a real fix.
