### ISSUE TITLE
Latest update broke a number of things

### ISSUE THREAD

**Issue by cyrusdaboo** [DonJayamanne/gitHistoryVSCode#435] opened 2020-02-11 19:48 UTC
1. The Commits view in the Explorer no longer appears. I have the "Hide Commit View Explorer" off in settings.

2. Clicking on commits in the history view does not always bring up the commit details pane at the bottom. Usually the top commit works, but then the next few do not (a click on them does nothing). At some point a click further down the list does work.

**Comment by sly1061101** [comment] 2020-02-11 20:11
+1

**Comment by ole1986** [comment] 2020-02-12 19:41
@cyrusdaboo I hope point 2 from your list has also been resolved with commit 645f0a4.

Otherwise please let me know through this issue and provide additional info if possible.
Thank you

**Comment by cyrusdaboo** [comment] 2020-02-13 15:52
Issue #1 is fixed - thanks.

Issue #2 is still a problem. I spotted the web server URL in the history output and opened that in Safari and opened the debug console there. When I click on a commit that does not show I see this:
```
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (451b6bd7c944200dd8b4d71973d6824a502ea41a, line 0)
[Error] Git History: Result failed
	(anonymous function) (bundle.js:54:1018521)
	promiseReactionJob
[Error] Error: Request failed with status code 500
(anonymous function) — bundle.js:15:13005
(anonymous function) — bundle.js:54:4279
(anonymous function) — bundle.js:15:11929

	(anonymous function) (bundle.js:54:1018565)
	promiseReactionJob
```

Is there additional logging on the server that I can grab?

One other thing that may be relevant: it seems that most of the commits that fail to appear have a commit message that includes an angle-bracketed URI at the start:

`<xyz://problem/1234> Commit message here`

**Comment by ole1986** [comment] 2020-02-13 16:13
Unfortunately I could not reproduce it with such commit message.

You can try toopen the Developer Webview and check the response (in the "Network" section) after clicking on the commit

![image](https://user-images.githubusercontent.com/4850116/74454255-e7829b00-4e83-11ea-8b19-329713b3056b.png)


To open the Developer Webview, press F1 and enter "Open Webview Developer Tools"

![image](https://user-images.githubusercontent.com/4850116/74454352-0bde7780-4e84-11ea-9c3a-d43e5f699904.png)

**Comment by cyrusdaboo** [comment] 2020-02-13 17:24
<img width="1183" alt="Screen Shot 2020-02-13 at 12 21 56 PM" src="https://user-images.githubusercontent.com/13540930/74460774-74652e80-4e5b-11ea-90ef-03271afddc2e.png">
 The response is just an empty JSON object.

Another possibility: I think the ones that are failing have multi-line commit messages. I do have one or two with the <url> prefix that are a single line message and those seem to display OK. But the other <url> ones are all multi-line (generated from a code review tool) and fail.

**Comment by chrisbarnes** [comment] 2020-02-13 20:08
I'm seeing a huge CPU spike when I try to view the history after the latest update.

**Comment by ole1986** [comment] 2020-02-13 21:31
@chrisbarnes does the CPU spike also occurs when refreshing the history view only?

**Comment by ole1986** [comment] 2020-02-14 07:45
something similar to the below?

![image](https://user-images.githubusercontent.com/4850116/74510983-345a8600-4f05-11ea-963e-25b6fe63231e.png)

The error seem to occur in src/server/apiController.ts starting at line [117](https://github.com/DonJayamanne/gitHistoryVSCode/blob/master/src/server/apiController.ts#L117). But unfortunately I could not reproduce it.

Is there any chance we can get access to an excerpt of the repository or you can debug the git history code yourself?

**Comment by cyrusdaboo** [comment] 2020-02-14 16:21
I have identified the problem. It seems to be caused by parsing a commit that looks like this:
```
git show --pretty=oneline --decorate=full --numstat 475cb867d4ebd92f6640fa54a61a90bffeff8977  (completed in 0.05s)
95E9659B-27DC-43C4-A717-D75969757EA527a3c4579a1214271f5dad1e52c366d6919dcf1b95E9659B-27DC-43C4-A717-D75969757EA627a3c457995E9659B-27DC-43C4-A717-D75969757EA6HEAD -> refs/heads/xxxxxxxxxxxxxxx395E9659B-27DC-43C4-A717-D75969757EA6xxxxxxxxxxx95E9659B-27DC-43C4-A717-D75969757EA6xxxxxxxxxxxxxxxx95E9659B-27DC-43C4-A717-D75969757EA6157878196095E9659B-27DC-43C4-A717-D75969757EA6xxxxxxxxxxx95E9659B-27DC-43C4-A717-D75969757EA6xxxxxxxxxxxxxxxx95E9659B-27DC-43C4-A717-D75969757EA6158164208995E9659B-27DC-43C4-A717-D75969757EA6xxxxxxx:
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

xxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxxxxx
xxxxxxxxxxxxxx

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
95E9659B-27DC-43C4-A717-D75969757EA695E9659B-27DC-43C4-A717-D75969757EA6475cb867d4ebd92f6640fa54a61a90bffeff897795E9659B-27DC-43C4-A717-D75969757EA6475cb867d95E9659B-27DC-43C4-A717-D75969757EA6c4513d7d806f7008c4f1f905bddb200443ebcccf95E9659B-27DC-43C4-A717-D75969757EA6c4513d7d895E9659B-27DC-43C4-A717-D75969757EA6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx395E9659B-27DC-43C4-A717-D75969757EA695E9659B-27DC-43C4-A717-D75969757EA795E9659B-27DC-43C4-A717-D75969757EA695E9659B-27DC-43C4-A717-D75969757EA6

2	1	xxxxxxxx
1	1	xxxxxxxxxx
1	1	xxxxxxxxxxxx
```

Note how there are multiple blank lines in the comment (sorry had to 'x' out all the details).

in `src/adapter/repository/git.ts` line 222 there is this:

`const filesWithNumStat = commitOutput.split("\n\n", 2)[1];`

That assumes that the file list appears after the first `\n\n`. That is not the case for the commit message with blank lines. I replaced that line of code with the following:

`const filesWithNumStat = commitOutput.slice(commitOutput.lastIndexOf(ITEM_ENTRY_SEPARATOR)).split("\n\n", 2)[1];`

That does the file list split after the last item separator in the commit output and correctly returns the file list.

With that change in place I am able to see all commit details again.

I will leave you to judge whether that is the best way to fix this issue, and whether there are other places that might be impacted by the blank line commit message parsing.

**Comment by ole1986** [comment] 2020-02-14 16:57
Good Job. I will apply a hotfix for it

**Closed** 2020-02-15 09:13 UTC
Labels: bug
