### ISSUE TITLE
"Git History" on virtual remote environment doesn't work through "Remote Development".

### ISSUE THREAD

**Issue by SachKoubyou** [DonJayamanne/gitHistoryVSCode#388] opened 2019-06-10 06:37 UTC
Issue Type: <b>Bug</b>

Install extensions "Remote Development" and "git history" on host OS(windows10).
Install git on remote OS(ubuntu18.04.2 on virtualbox 5.2.22).
Install extensions "git history" on remote OS through "Remote Development".
Clone any repository on remote OS with git.
Open the folder of the repository with VSCode on local OS.
Execute "git history" with command "Git: View History(git log)".
Nothing is displayed on the tab like the following issue.
https://github.com/DonJayamanne/gitHistoryVSCode/issues/377

But, "git history" that directly installed on remote OS(without using remote-development) is working correctly.

Extension version: 0.4.6
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.18.0-21-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (2.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|SSH: ubuntu|
|OS|Linux x64 4.18.0-21-generic|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (1 x 3192)|
|Memory (System)|1.95GB (0.11GB free)|
|VM|100%|
</details>

**Comment by dusty-phillips** [comment] 2019-08-02 16:50
duplicate of #379

**Closed** 2019-11-29 23:08 UTC
