### ISSUE TITLE
Option : Git History (git log) : keep state on switch tab or disable refresh

### ISSUE THREAD

**Issue by rdewolff** [DonJayamanne/gitHistoryVSCode#125] opened 2017-04-30 16:39 UTC
Hello!

First, thanks for your work! I have noticed something that could be improved. Please see my description below.

**Actual behaviour :** when displaying Git History (git log) and clicking on a specific commit, the bottom window shows the details of the specific commit. When switching to another tab and going back to the "Git History (git log)" tab, the details are not shown anymore.

**Wanted behaviour :** when switching to another tab and going back to the "Git History (git log)" tab, the previously displayed details should be still visible.

**Idea :** either have an option to disable the auto refresh of the tab when switching tab, or keep the displayed tab state.

What do you think, would that be possible ?

**Comment by ajaygm** [comment] 2017-06-30 13:07
#122 is possibly a duplicate of this.

**Comment by ajaygm** [comment] 2017-06-30 13:23
Refer #51 for more details.

**Comment by DonJayamanne** [comment] 2020-02-22 22:43
Closing this issue due to inactivity

**Closed by DonJayamanne** 2020-02-22 22:43 UTC
